server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php index.html;

    client_max_body_size 20M;

    location = /admin {
        return 301 /admin/;
    }

    location /admin/ {
        index index.html;
        try_files $uri $uri/ /admin/index.html;
    }

    location = /cabinet {
        return 301 /cabinet/;
    }

    location /cabinet/ {
        index cabinet.html index.html;
        try_files $uri $uri/ /cabinet/cabinet.html;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_hide_header X-Powered-By;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
